"""alter_food_item_table

Revision ID: 5182c6b12663
Revises: d70c9ec80e58
Create Date: 2021-03-26 09:22:13.550886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5182c6b12663'
down_revision = 'd70c9ec80e58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FoodItem', sa.Column('per_unit_measurement', sa.Float(), nullable=True))
    op.add_column('FoodItem', sa.Column('measurement_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_FoodItem_measurement_id'), 'FoodItem', ['measurement_id'], unique=False)
    op.create_foreign_key(None, 'FoodItem', 'Measurement', ['measurement_id'], ['measurement_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('FoodItem', 'per_unit_measurement')
    op.drop_constraint('FoodItem_measurement_id_fkey', 'FoodItem', type_='foreignkey')
    op.drop_index(op.f('ix_FoodItem_measurement_id'), table_name='FoodItem')
    op.drop_column('FoodItem', 'measurement_id')
    # ### end Alembic commands ###
