"""create_measurement_table

Revision ID: 5c1c1fa1517c
Revises: 73c80070ebe8
Create Date: 2021-03-20 23:29:58.635446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c1c1fa1517c'
down_revision = '73c80070ebe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Measurement',
    sa.Column('measurement_id', sa.Integer(), nullable=False),
    sa.Column('measurement_description', sa.String(), nullable=True),
    sa.Column('measurement_quantity', sa.Float(), nullable=True),
    sa.Column('suffix', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('measurement_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Measurement')
    # ### end Alembic commands ###
