"""alter_food_table

Revision ID: 5dad3abc8199
Revises: 7ec758cdf625
Create Date: 2021-03-31 13:38:56.257191

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql.ddl import CreateSequence, DropSequence


# revision identifiers, used by Alembic.
revision = '5dad3abc8199'
down_revision = '7ec758cdf625'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(CreateSequence(sa.schema.Sequence("food_food_index_seq")))
    op.add_column('Food', sa.Column('food_index', sa.Integer(), server_default=sa.text("nextval('food_food_index_seq'::regclass)"),nullable=False))
    op.create_index(op.f('ix_Food_index'), 'Food', ['food_index'], unique=True)
    op.drop_index('ix_Food_food_id', table_name='Food')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_Food_food_id', 'Food', ['food_id'], unique=True)
    op.drop_index(op.f('ix_Food_index'), table_name='Food')
    op.drop_column('Food', 'food_index')
    op.execute(DropSequence(sa.schema.Sequence("food_food_index_seq")))
    # ### end Alembic commands ###
