"""alter_measurement_column_desc

Revision ID: 7ec758cdf625
Revises: 5182c6b12663
Create Date: 2021-03-26 10:31:50.292767

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7ec758cdf625'
down_revision = '5182c6b12663'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Measurement', sa.Column('measurement_conversion_to_g', sa.Float(), nullable=True))
    op.drop_column('Measurement', 'measurement_quantity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Measurement', sa.Column('measurement_quantity', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('Measurement', 'measurement_conversion_to_g')
    # ### end Alembic commands ###
