"""add password update date column to user table

Revision ID: 930131d4fd37
Revises: d8ea7a11312b
Create Date: 2020-10-29 17:11:13.082422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '930131d4fd37'
down_revision = 'd8ea7a11312b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('password_updated_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'password_updated_date')
    # ### end Alembic commands ###
