"""add clinician assignment table, remove clinician_id, add name column to user table

Revision ID: ae0f6b689768
Revises: c32416539de7
Create Date: 2020-10-26 09:46:04.564041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae0f6b689768'
down_revision = 'c32416539de7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ClinicianAssignment',
    sa.Column('clinician_assignment_id', sa.Integer(), nullable=False),
    sa.Column('clinician_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assignment_accepted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['clinician_id'], ['User.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('clinician_assignment_id')
    )
    op.create_index(op.f('ix_ClinicianAssignment_clinician_assignment_id'), 'ClinicianAssignment', ['clinician_assignment_id'], unique=False)
    op.add_column('User', sa.Column('name', sa.String(), nullable=True))
    op.drop_constraint('User_clinician_id_fkey', 'User', type_='foreignkey')
    op.drop_column('User', 'clinician_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('clinician_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('User_clinician_id_fkey', 'User', 'User', ['clinician_id'], ['user_id'])
    op.drop_column('User', 'name')
    op.drop_index(op.f('ix_ClinicianAssignment_clinician_assignment_id'), table_name='ClinicianAssignment')
    op.drop_table('ClinicianAssignment')
    # ### end Alembic commands ###
