"""add contact information to user table

Revision ID: d8ea7a11312b
Revises: ae0f6b689768
Create Date: 2020-10-29 16:41:49.609169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8ea7a11312b'
down_revision = 'ae0f6b689768'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('contact_information', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'contact_information')
    # ### end Alembic commands ###
