version: '3.8'
services:
  app:
    restart: always
    build: ./application
    environment: 
      # Set to 1 to initiate database initial migrations
      INITIAL: 0
      # Set to 1 for development mode else 0 to disable reloader
      DEV : 0
    networks:
      - healthapp
    ports: 
      - 9000:9000
    depends_on:
      - db
  db:
    image: postgres:alpine
    restart: always
    environment: 
      # POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      # POSTGRES_USER_FILE: /run/secrets/db_user
      # POSTGRES_DB_FILE: /run/secrets/db_name
      POSTGRES_PASSWORD: user
      POSTGRES_USER: user
      POSTGRES_DB: app
    networks:
      - healthapp
    volumes:
      - pqlvolume:/var/lib/postgresql/data
    ports: 
      - 5432:5432
    secrets:
      - db_password
      - db_user
      - db_name
secrets:
  db_password:
    file: secrets/pg-password.txt
  db_user:
    file: secrets/pg-user.txt
  db_name:
    file: secrets/pg-db.txt

networks:
  healthapp:
volumes:
  pqlvolume:
